#!/usr/bin/env bash
#  check: Ensure that proper formatting has been used.

# Ensure we run from the lesson directory
cd "$( dirname "${BASH_SOURCE[0]}" )" && cd ..

# Show all of the FIXMEs in the lessons content
grep -i -n FIXME ??-*.md
